title: "Siegfried Nacion | B.S. Computer Science & Data Science"
author: "Siegfried N"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "projects.md", title: "Projects"}
  - {url: "https://drive.google.com/file/d/1nBH6JSE0OrKTcsUM0K1VgjIeXJt5Q07V/view?usp=sharing", title: "My Resume"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:siegproduction1@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/BigSiegge"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/siegfriedn/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
